#!/usr/bin/env bash
#To infinity and beyond, then display "I am invincible!!!" when receiving SIGTERM signal

while true
do
    echo 'To infinity and beyond'
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
