#!/usr/bin/env bash
#Write Best School 10 times using while but on the 4th put bad luck and on the 8th put good luck
i=1
while [[ $i -le 10 ]]
do
        echo "Best School"
        if
        [[ $i -eq 4 ]];
        then
                echo "bad luck"
        	else
        	[[ $i -eq 9 ]];
       	        	echo "good luck"
        	fi
        	((i++))
done
