#!/usr/bin/env bash
#Script about the school files and if they are empty

i="school"
if [ -e "$i" ]
then
    echo "school file exists"
    if [ ! -s "$i" ]
    then
	echo "school file is empty"
    else
	echo "school file is not empty"
    fi
    if [ -f "$i" ]
    then
	echo "school is a regular file"
    fi
else
echo "school file does not exist"
fi
